name: "run tests"
on:
  [push, pull_request, workflow_dispatch]

jobs:
  perl_tester:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        perl-version:
          - "5.14"
          - "5.16"
          - "5.18"
          - "5.20"
          - "5.22"
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"
          - "5.32"
          - "5.34"
          - "5.36"
        exclude:
          - os: windows-latest
            perl-version: "5.18"
          - os: windows-latest
            perl-version: "5.20"
          - os: windows-latest
            perl-version: "5.22"
          - os: windows-latest
            perl-version: "5.24"
          - os: windows-latest
            perl-version: "5.26"

    runs-on: ${{ matrix.os }}
    name: "perl v${{ matrix.perl-version }} on ${{ matrix.os }}"

    steps:
      - uses: actions/checkout@v3
      - name: "Set up perl"
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: cpanm --installdeps --with-develop --notest .
      - run: cpanm --installdeps --with-develop --notest .
      - run: perl Makefile.PL
      - run: make test
